"""List of constants used in Santorini."""
import sys
import os

BOARD_SIZE = 6
TOTAL_NUM_WORKERS = 4
WORKER_NUM_PER_PLAYER = 2
TOTAL_PLAYER_NUM = 2
MAX_HEIGHT = 4
MOVE_HEIGHT_DIFFERENCE = 1
PLACEMENT_WAITTIME = 6
TURN_WAITTIME = 6
OBSERVER_WAITTIME = 2
NAME_WAITTIME = 3

CONNECTION_WAIT_TIME = 15 #3 minutes